// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _07_MVC_EmployeeEntity.Contexts;

#nullable disable

namespace _07_MVC_EmployeeEntity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230928075220_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_07_MVC_EmployeeEntity.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "USA",
                            Brand = "Apple",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Address = "USA",
                            Brand = "Nvidia",
                            Name = "Nvidia"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Japan",
                            Brand = "Nissan",
                            Name = "Nissan"
                        });
                });

            modelBuilder.Entity("_07_MVC_EmployeeEntity.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            FirstName = "Sefa",
                            LastName = "ATTİLA"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 2,
                            FirstName = "Ali",
                            LastName = "Gündüz"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 3,
                            FirstName = "Mehmet",
                            LastName = "Kısa"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 1,
                            FirstName = "Ahmet",
                            LastName = "Yaşar"
                        });
                });

            modelBuilder.Entity("_07_MVC_EmployeeEntity.Entities.Employee", b =>
                {
                    b.HasOne("_07_MVC_EmployeeEntity.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("_07_MVC_EmployeeEntity.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
